### ISSUE TITLE
Migrate authentication to Reactside

### ISSUE THREAD

**Issue by emarchak** [CivicTechTO/women-and-color-backend#24]
## Description
When we first set up the website, all the account pages like login, registration, password reset, etc. were all created on the built-in templates from Django's allauth module. It was a good way to get up and running quickly, but it meant that our frontend and backend weren't completely separate.

Let's fix that. We want to move all the authentication pages into React and use token-based authentication instead of session-based authentication.

- [x] install and use django-rest-framework-jwt
- [x] install and use django-cors-headers
- [ ] do we need to reconfigure the CRSF token?
- [ ] do we need to change the permissions logic? (in the profile model and featured talks model)
- [ ] remove frontend app and unused allauth templates

**Comment by s-kennedy** [comment]
in progress on the `infrastructure_update` branch
